### ISSUE TITLE
对于 Script/Passage 相关的 Mod 支持

### ISSUE THREAD

**Issue by hxdnshx** [Lyoko-Jeremie/sugarcube-2-ModLoader#1]
注意到下面定义：
https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader/blob/f41c498309e44b9c8d20fc899745e066b0257fe0/src/BeforeSC2/SC2DataInfoCache.ts#L17-L27
中，`content` 字段是字符串类型。在本地化Mod 的实现中，对其的内容进行了直接的修改，并进行替换。

而在一般的 Mod 场景中，“在原本的 Passage 中增加新的选项 ”是一个比较普遍的场景。对于这个场景，ModLoader 是否考虑增加形如 AST 形式的 Passage 之类的支持？以避免类似 “i18n 导致Mod对 Passage 的匹配失效” “两个相同Mod都是添加新的Btn，但是由于影响到了regex匹配的特征串，导致互不兼容” 等问题过于频繁的发生？或者说对于这种场景，ModLoader推荐的解决方案是怎样的？

**Comment by Lyoko-Jeremie** [comment]
这个问题现在暂时没有找到最佳答案。 
 modloader在设计上也没有任何推荐的解决方案。  
modloader在设计上支持任何mod读取并修改passage，所以任何算法都可以实现为一个独立的mod，以addon的形式加载进来并和其他算法共同工作。

以下是预置的两个不同的替换mod的例子：

https://github.com/Lyoko-Jeremie/Degrees-of-Lewdity_Mod_TweeReplacer  

https://github.com/Lyoko-Jeremie/Degrees-of-Lewdity_Mod_ReplacePatch  


如果你有更好的解决方法，欢迎共享出来。
