### ISSUE TITLE
关于 modList 的维护

### ISSUE THREAD

**Issue by hxdnshx** [Lyoko-Jeremie/sugarcube-2-ModLoader#3]
我尝试基于 ModLoader 制作了一个 Mod，那么对于 remote 的 modlist ，计划采取什么样的维护方针，应当怎样将自己的 Mod 加入这个列表中？

**Comment by Lyoko-Jeremie** [comment]
mod 有这4个来源 https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader#%E5%8A%A0%E8%BD%BD%E9%A1%BA%E5%BA%8F

这个 ModLoader 项目文件中的 modlist 只适用于预加载进html的mod【local】。
而对于远程加载的【remote】，`modList.json` 文件的格式与项目中的这个相同，唯一需要注意的是路径需要满足 fetch 的路径语法。远程加载的源码参见：
https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader/blob/dffd87657683b29ee663ac8279dbec8ce6611466/src/BeforeSC2/ModZipReader.ts#L698-L733

其中`modFileZipPath` https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader/blob/dffd87657683b29ee663ac8279dbec8ce6611466/src/BeforeSC2/ModZipReader.ts#L714 就是在 `modList.json` 文件中列出的路径，`RemoteLoader` 会直接使用fetch访问服务器的这个路径来下载zip文件并加载mod。

---

举例：

```json
[
  "aaa.mod.zip",  // 从html同一目录加载 aaa.mod.zip
  "/rrr.mod.zip",   // 从web服务器根目录加载 rrr.mod.zip
  "./ddd/ccc.mod.zip",  // 从html所在目录下的ddd文件夹中加载 ccc.mod.zip
  "../../uuu.mod.zip",  // 从html所在目录的父目录的父目录加载 uuu.mod.zip
  "http://aaa.bbb.ccc/mmm.mod.zip"  // 从网站 aaa.bbb.ccc 加载 mmm.mod.zip
]
```

---

有关 `modList.json` 的设计是这样的。
* 对于需要打包自己的“整合包”的用户，可以直接在打包时指定一个自定义的 `modList.json` 来将想要的mod全部打包进html。【local】
* 对于自己设立了web服务器的用户，可以在web服务器上的与html同一目录下放置一个`modList.json`文件，这样在启动时就会由`RemoteLoader`去加载这个`modList.json`文件中指定的mod。【remote】
* 对于终端用户（玩家），在打开游戏后就会默认得到以上两个【local】+【remote】的mod，玩家自己可以通过mod管理器的界面再加载自己想要的mod。【IndexDB】

以上三个中，如果存在同名mod，则会存在覆盖关系，【remote】会覆盖【local】中的同名mod，而【IndexDB】
会覆盖【local】+【remote】的同名mod。  
也就是说，如果【local】和【remote】都存在mod A ，则最终生效的是【remote】的mod A。如果用户再自己加载一个mod A，则最终生效的是用户加载的这个mod A。

**Comment by Meow0x7E** [comment]
> mod 有这4个来源 https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader#%E5%8A%A0%E8%BD%BD%E9%A1%BA%E5%BA%8F
> 
> 这个 ModLoader 项目文件中的 modlist 只适用于预加载进html的mod【local】。 而对于远程加载的【remote】，`modList.json` 文件的格式与项目中的这个相同，唯一需要注意的是路径需要满足 fetch 的路径语法。远程加载的源码参见：
> 
> https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader/blob/dffd87657683b29ee663ac8279dbec8ce6611466/src/BeforeSC2/ModZipReader.ts#L698-L733
> 
> 其中`modFileZipPath`
> 
> https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader/blob/dffd87657683b29ee663ac8279dbec8ce6611466/src/BeforeSC2/ModZipReader.ts#L714
> 
> 就是在 `modList.json` 文件中列出的路径，`RemoteLoader` 会直接使用fetch访问服务器的这个路径来下载zip文件并加载mod。
> 举例：
> 
> ```json
> [
>   "aaa.mod.zip",  // 从html同一目录加载 aaa.mod.zip
>   "/rrr.mod.zip",   // 从web服务器根目录加载 rrr.mod.zip
>   "./ddd/ccc.mod.zip",  // 从html所在目录下的ddd文件夹中加载 ccc.mod.zip
>   "../../uuu.mod.zip",  // 从html所在目录的父目录的父目录加载 uuu.mod.zip
>   "http://aaa.bbb.ccc/mmm.mod.zip"  // 从网站 aaa.bbb.ccc 加载 mmm.mod.zip
> ]
> ```
> 
> 有关 `modList.json` 的设计是这样的。
> 
> * 对于需要打包自己的“整合包”的用户，可以直接在打包时指定一个自定义的 `modList.json` 来将想要的mod全部打包进html。【local】
> * 对于自己设立了web服务器的用户，可以在web服务器上的与html同一目录下放置一个`modList.json`文件，这样在启动时就会由`RemoteLoader`去加载这个`modList.json`文件中指定的mod。【remote】
> * 对于终端用户（玩家），在打开游戏后就会默认得到以上两个【local】+【remote】的mod，玩家自己可以通过mod管理器的界面再加载自己想要的mod。【IndexDB】
> 
> 以上三个中，如果存在同名mod，则会存在覆盖关系，【remote】会覆盖【local】中的同名mod，而【IndexDB】 会覆盖【local】+【remote】的同名mod。 也就是说，如果【local】和【remote】都存在mod A ，则最终生效的是【remote】的mod A。如果用户再自己加载一个mod A，则最终生效的是用户加载的这个mod A。

我觉得这个回答里关于 `modlist.json` 的 `RemoteLoader` 的举例部分可以加进项目的`README.md`里。最开始我因为 `Nginx` 在游戏加载时向我抱怨它找不到`modlist.json` 时让我产生了直接在服务器端准备好Mod的想法。看 `README.md` 时对这一部分产生了疑惑，因为它并没提到 `modlist.json` 应用在 `RemoteLoader` 时的编写方式
